### ISSUE TITLE
This card will not work with Home Assistant 2021.6.2

### ISSUE THREAD

**Issue by brinzlee** [clayauld/lovelace-darksky-card#4] opened 2021-06-06 10:14 UTC
**Describe the bug**
There is an error in the log and the page is blank with the darksky card in lovelace
I think this is to do with the new way LITelement is applied but I might be wrong. I know DarkSky has been discontinued but will you be updating the JS to make this work
Thanks

**Comment by jscherry** [comment] 2021-06-06 16:32
Having exact same issue since 2021.6.1

**Comment by DoctorOctagonapus** [comment] 2021-06-06 22:30
This has been discussed in various places and the consensus is it's that LitElement that's breaking it. There's a fixed version of the original card here: https://gist.github.com/Mariusthvdb/2f24cc40a6dac7e474c65e7412a4c418 but even with the config supplied in the comment I've not had any joy getting it to work.

**Comment by Sudo-Rob** [comment] 2021-06-07 17:44
I just tried the @Mariusthvdb JS file and was unsuccessful.  Both it and the @clayauld version post the identical error from the HACS debug log.

> ERROR (MainThread) [frontend.js.latest.202106030] http://192.168.0.xx:8123/local/community/lovelace-darksky-card/lovelace-darksky-card.js:719:9 TypeError: root is null

**Comment by DoctorOctagonapus** [comment] 2021-06-07 18:39
> ERROR (MainThread) [frontend.js.latest.202106030] http://192.168.0.xx:8123/local/community/lovelace-darksky-card/lovelace-darksky-card.js:719:9 TypeError: root is null

That's interesting, mine gets a different error: https://.../hacsfiles/lovelace-darksky-card/lovelace-darksky-card.js:719:14 Uncaught TypeError: Cannot read property 'childElementCount' of null

**Comment by Sudo-Rob** [comment] 2021-06-07 19:15
I'm guessing the variable associated with either error is unpopulated.  I see entities with "unknown" in Developer Tools.

I should add that I clear the browser cache before drawing any conclusions.  When I do, the dashboard minus the weather card is displayed.

**Comment by DoctorOctagonapus** [comment] 2021-06-07 21:48
Huh I should have checked that. I'm getting a load of unknown sensors, namely sensor.dark_sky_precip and sensor.dark_sky_precip_accumulation_0d through sensor.dark_sky_precip_accumulation_5d. All the others are returning values.

**Comment by Sudo-Rob** [comment] 2021-06-07 22:13
For the record:
HA installation:  x86 Supervised with compliant Debian, 2021.6.2
Browsers: Firefox 89.0 (64-bit) on Windows-10 Pro, and Safari 14 on iOS 14.6

**Comment by DoctorOctagonapus** [comment] 2021-06-07 22:54
HassOS on a Pi4 here, browsing on Chrome on MacOS and the Android app.

**Comment by clayauld** [comment] 2021-06-08 00:35
I'm seeing this issue on my instance now too. Let me see if I can find a solution....

**Comment by Sudo-Rob** [comment] 2021-06-08 01:43
@clayauld:

Don't know if you're aware of these, but just in case...

[https://developers.home-assistant.io/blog/2021/05/19/lit-2.0/](https://developers.home-assistant.io/blog/2021/05/19/lit-2.0/)

[https://lit.dev/docs/releases/upgrade/](https://lit.dev/docs/releases/upgrade/)

**Comment by clayauld** [comment] 2021-06-08 05:23
Thanks. That appears to be the issue, or one of them. I'm working on a fix.

**Comment by clayauld** [comment] 2021-06-10 08:11
Please try reinstalling with the new updates I just pushed tonight. Its fixed for me, but I want to make sure its working for others.

**Comment by vk2him** [comment] 2021-06-10 08:45
I realise I'm probably unsupported, however I modified your original lovelace-darksky-card.js to use my weather station as a source of the weather data. Would you mind sharing the fix you implemented please so I can attempt to modify my unsupported modified file? Thanks

**Comment by brinzlee** [comment] 2021-06-10 09:43
@clayauld Many thanks for updating the code.....It works perfectly.......Do you have any idea how long DarkSky will work for before Apple pulls the plug on it ?

**Comment by BVGorp** [comment] 2021-06-10 10:31
Indeed the fix works.

from the darksky website:

Update: Support for the Dark Sky API service for existing customers will continue until the end of 2022. The iOS app and Dark Sky website will also be available until the end of 2022.

**Comment by DoctorOctagonapus** [comment] 2021-06-10 14:57
Thanks for that, I'm seeing it absolutely fine here, though not on my phone. Looks like it's still caching the borked version for some reason.

**Comment by Sudo-Rob** [comment] 2021-06-10 16:27
The card is working, but I see an error in HACS:
![image](https://user-images.githubusercontent.com/56487711/121561778-cd5cbc80-c9e6-11eb-985c-98bcd6a81aa2.png)

Sometimes when I see this message, it can be caused by a remnant in the browser cache.  Clearing it did not resolve the issue.

I'm also seeing this in the HA log : `ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139656901325776] Received invalid command: lovelace/resources/create`

**Comment by BVGorp** [comment] 2021-06-10 16:31
> 
> 
> Thanks for that, I'm seeing it absolutely fine here, though not on my phone. Looks like it's still caching the borked version for some reason.

On phone in app settings clear frontend cache

**Comment by clayauld** [comment] 2021-06-10 17:04
> The card is working, but I see an error in HACS:
> ![image](https://user-images.githubusercontent.com/56487711/121561778-cd5cbc80-c9e6-11eb-985c-98bcd6a81aa2.png)
> 
> Sometimes when I see this message, it can be caused by a remnant in the browser cache.  Clearing it did not resolve the issue.
> 
> I'm also seeing this in the HA log : `ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139656901325776] Received invalid command: lovelace/resources/create`

Please select the menu button and reinstall. That should fix the issue for you. 

![Screenshot_20210610-090341.png](https://user-images.githubusercontent.com/2290528/121567228-d17ae100-c9ca-11eb-94f5-d6f526e590a7.png)

**Comment by Sudo-Rob** [comment] 2021-06-10 17:18
Hmm.  I've already done that.  Just to make sure, I did it again, which in the process also reloads the resource and clears the cache.  No change.  Additionally, I've performed a few Server Restarts followed by clearing the cache, which were unsuccessful.

Also, the re-installation results in another instance of the same error in the HA log.  If no one else has the issue, I must have some other error in my config files.

Color me frustrated.

**Comment by fallen293** [comment] 2021-06-10 17:25
@Sudo-Rob  I have the same issue as you. Installed the new version, no change. Reinstalled and no change

**Comment by Sudo-Rob** [comment] 2021-06-10 17:50
@fallen293:

Just to be clear, the card is working.  The issue I have is with an error in the HA log which appears related to an error message in HACS.  

If you can't see the card,  it's probably related to the need to clear the browser or app cache:

If you use the iOS HA Companion app, go to Side bar> app configuration > debugging > reset frontend cache.  Then fully close the app and restart it.  

For a browser, you'll either need to either use CTRL+F5, or go to the settings to clear it.

**Comment by fallen293** [comment] 2021-06-10 20:21
@Sudo-Rob  I cleared the cache earlier, but it appeared to work now, thanks :)

**Comment by clayauld** [comment] 2021-06-10 21:37
> 
> 
> I realise I'm probably unsupported, however I modified your original lovelace-darksky-card.js to use my weather station as a source of the weather data. Would you mind sharing the fix you implemented please so I can attempt to modify my unsupported modified file? Thanks

@vk2him 
The fix came from here: https://gist.github.com/Mariusthvdb/2f24cc40a6dac7e474c65e7412a4c418

You can also look at my commit 57b08758ce3d4f2f14c8b65cc88cae526257a3b4 to see what the changes were.

**Comment by clayauld** [comment] 2021-06-10 21:37
Closing this as the issue should be resolved now.

**Closed by clayauld** 2021-06-10 21:37 UTC

**Comment by vk2him** [comment] 2021-06-11 01:31
> > I realise I'm probably unsupported, however I modified your original lovelace-darksky-card.js to use my weather station as a source of the weather data. Would you mind sharing the fix you implemented please so I can attempt to modify my unsupported modified file? Thanks
> 
> @vk2him
> The fix came from here: https://gist.github.com/Mariusthvdb/2f24cc40a6dac7e474c65e7412a4c418
> 
> You can also look at my commit [57b0875](https://github.com/clayauld/lovelace-darksky-card/commit/57b08758ce3d4f2f14c8b65cc88cae526257a3b4) to see what the changes were.

Thanks for that - I now have my modified version working. For anyone else in the same situation, there are two main changes:

1) var LitElement and associated customElements towards the top of the script

2) The set hass(hass)  section towards the end of the script that refreshes when a state change occurs needs modification by  replacing code

This is what mine looks like using data from my weather station

![Screen Shot](https://user-images.githubusercontent.com/22878629/121617334-06109a80-caa8-11eb-900b-f82145aa40b1.jpg)
